### ISSUE TITLE
Xtra-Large Icons for Windows please?

### ISSUE THREAD

**Issue by FYPH2016** [denydias/coldhex#1]
Greetings Denydias.  Absolutely love your SIFR icon set for LibreOffice.  

I'm having a problem with ALL the button icons/themes in LO 5.2.whatever and Windows 10.   In general the largest offered size is still too small for some of us.  We are likely older using a higher resolution screen.   Attached is an example of easier on the eye sizing.

If this isn't too much work I (and others) would really appreciate.  I've given $20 for Libre and will do so each year (promise!) if this critical feature emerges somehow. 

All my best.

![026f49d2c1](https://cloud.githubusercontent.com/assets/22508284/19023548/9e50378c-88a5-11e6-8087-2d5be79ba26a.jpg)

**Comment by denydias** [comment]
Hi, @FYPH2016!

I'm glad you've liked this hack. Thank you.

Unfortunately, I'm not the author of those icons. I have just come up with a way to convert them to a better monochrome look.

To achieve what you want, you'll need the vector files for the whole iconset (probably svg and which I don't have). However, the iconset publicly available is a raster one (a bunch of png files). Although we can upscale it from those png files, the quality loss is going to be quite perceptible, just like it looks in your resized screenshot.

I think this is a request for the [real authors](https://github.com/LibreOffice/core/blob/master/icon-themes/sifr/AUTHORS) of this iconset. The source repository for those icons is [here](https://github.com/LibreOffice/core/tree/master/icon-themes/sifr).

I wish you luck with this one.

**Comment by FYPH2016** [comment]
ah! the plot THICKENS...

thank you

**Comment by denydias** [comment]
LOL! Now it's solved, @FYPH2016. You've got the authors. ;)
